### ISSUE TITLE
Missing license info

### ISSUE THREAD

**Issue by skizzerz** [frozenMustelid/pfsb#2]
The OGL isn’t a software license. While it covers much of the content/data you are using, you should have a license for the source code itself as well.

**Comment by frozenMustelid** [comment]
Technically speaking, it can be a software license. WOTC had a part of their website that covered this particular usage. It's suboptimal, but it can work. (https://web.archive.org/web/20171028183452/https://www.wizards.com/default.asp?x=d20/oglfaq/20040123i)

I'm working on ideas to remove the OGL legal necessity from the source code. My best one so far is to offload all of the OGL stuff (creature info, other stuff to be implemented later) into external files hosted in a separate repository, that the PFSB Makefile grabs as part of the install process. The second repo would be OGL'ed, the original would be a license suitable for software. None of this is even close to being reality yet, though.


In the meantime, just go by the info in the readme: If you act like it's GPL/MIT/Similar copyleft license, I won't lawyer up, but that doesn't mean that somebody who actually could afford lawyers if they had the inclination won't.
